### ISSUE TITLE
Blank email templates should not be sent

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#61]
When the email template has an empty email body, then the email template should not be sent for recovering the cart.

**Comment by Chetna1510** [comment]
This issue has been fixed  and committed on Github: e3a3181f3293dbe40bda8538abed6497a3d871c8

**Comment by galakhyati** [comment]
The issue is still there. If the email template is blank, then the email is sent for abandoned cart reminder.
http://screencast.com/t/euMl0umgcjB

The issue is fixed for test email should not be sent when email template is empty.
